# ruff: noqa: E501
"""database v1 control static and semantic serving

Revision ID: 0001_database_v1
Revises:
Create Date: 2026-08-04 00:10:21.370876
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_database_v1"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Schemas and PostGIS are reviewed hand-written DDL that Alembic cannot infer.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE SCHEMA control")
    op.execute("CREATE SCHEMA static")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifact",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name="ck_artifact_sha256"),
        sa.CheckConstraint(
            "storage_key !~ '^(?:[A-Za-z]:|/|\\\\)'", name="ck_artifact_relative_key"
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_artifact_size"),
        sa.PrimaryKeyConstraint("sha256"),
        schema="control",
    )
    op.create_table(
        "build_spec",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_spec_sha256"),
        sa.CheckConstraint("schema_version > 0", name="ck_build_spec_schema_version"),
        sa.PrimaryKeyConstraint("sha256"),
        schema="control",
    )
    op.create_table(
        "source",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("adapter_kind", sa.String(length=64), nullable=False),
        sa.Column("licence", sa.Text(), nullable=True),
        sa.Column("retrieval_method", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="control",
    )
    op.create_table(
        "agency",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("fare_url", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("build_id", "agency_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "fare_system",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("fare_system_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("build_id", "fare_system_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "identifier_alias",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("observed_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("canonical_value", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint("valid_to IS NULL OR valid_to >= valid_from", name="ck_alias_validity"),
        sa.PrimaryKeyConstraint("build_id", "source_id", "namespace", "observed_id", "valid_from"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "location",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("parent_location_id", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("public_code", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("municipality_name", sa.Text(), nullable=True),
        sa.Column("district_name", sa.Text(), nullable=True),
        sa.Column("district_code", sa.String(length=16), nullable=True),
        sa.Column("nearby_place", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=3), nullable=True),
        sa.Column("coordinate_precision", sa.String(length=32), nullable=True),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("wheelchair_boarding", sa.SmallInteger(), nullable=True),
        sa.CheckConstraint(
            "(kind = 'boarding_point' AND parent_location_id IS NOT NULL) OR (kind <> 'boarding_point' AND parent_location_id IS NULL)",
            name="ck_location_parent",
        ),
        sa.CheckConstraint("domain IN ('surface','heavy_rail')", name="ck_location_domain"),
        sa.CheckConstraint(
            "kind IN ('stop_place','boarding_point','operational_point')", name="ck_location_kind"
        ),
        sa.CheckConstraint(
            "wheelchair_boarding IS NULL OR wheelchair_boarding BETWEEN 0 AND 2",
            name="ck_location_wheelchair",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "parent_location_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "location_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_static_location_position",
        "location",
        ["position"],
        unique=False,
        schema="static",
        postgresql_using="gist",
    )
    op.create_table(
        "operational_journey",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_journey_id", sa.Text(), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=16), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "domain IN ('surface','heavy_rail')", name="ck_operational_journey_domain"
        ),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_operational_journey_snapshot"
        ),
        sa.PrimaryKeyConstraint("build_id", "source_id", "source_journey_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "operational_location",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_location_id", sa.Text(), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("country_code", sa.String(length=3), nullable=False),
        sa.Column("primary_code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("coordinate_source", sa.String(length=64), nullable=True),
        sa.Column("coordinate_source_object_id", sa.Text(), nullable=True),
        sa.Column("coordinate_match_method", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_operational_location_snapshot"
        ),
        sa.PrimaryKeyConstraint("build_id", "source_id", "source_location_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_operational_location_position",
        "operational_location",
        ["position"],
        unique=False,
        schema="static",
        postgresql_using="gist",
    )
    op.create_table(
        "selected_field_provenance",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("field_name", sa.String(length=96), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.Column("selection_rule", sa.String(length=160), nullable=False),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_selected_provenance_snapshot"
        ),
        sa.PrimaryKeyConstraint("build_id", "object_type", "object_key", "field_name"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "service_calendar",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("weekday_mask", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_calendar_validity"),
        sa.CheckConstraint("weekday_mask BETWEEN 0 AND 127", name="ck_calendar_weekdays"),
        sa.PrimaryKeyConstraint("build_id", "service_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "service_note",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("note_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("service_note_type", sa.String(length=64), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('route_information','service_note','reservation')",
            name="ck_service_note_kind",
        ),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_service_note_snapshot"
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name="ck_service_note_validity",
        ),
        sa.PrimaryKeyConstraint("build_id", "note_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "shape",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("shape_id", sa.Text(), nullable=False),
        sa.Column("generation_method", sa.String(length=32), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="LINESTRING",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("build_id", "shape_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_static_shape_geometry",
        "shape",
        ["geometry"],
        unique=False,
        schema="static",
        postgresql_using="gist",
    )
    op.create_table(
        "source_entity_map",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("identifier_namespace", sa.String(length=64), nullable=False),
        sa.Column("entity_kind", sa.String(length=32), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.Column("public_id", sa.Text(), nullable=False),
        sa.CheckConstraint("identifier_namespace <> ''", name="ck_source_entity_namespace"),
        sa.PrimaryKeyConstraint(
            "build_id", "source_id", "identifier_namespace", "entity_kind", "source_object_id"
        ),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_source_entity_public",
        "source_entity_map",
        ["build_id", "entity_kind", "public_id"],
        unique=False,
        schema="static",
    )
    op.create_table(
        "travel_restriction_assignment",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=True),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.Column("source_route_stop_id", sa.Text(), nullable=False),
        sa.Column("call_sequence", sa.Integer(), nullable=True),
        sa.Column("group_code", sa.String(length=1), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(scope='route_stop' AND route_id IS NOT NULL AND trip_id IS NULL AND call_sequence IS NULL) OR (scope='trip_call' AND route_id IS NULL AND trip_id IS NOT NULL)",
            name="ck_travel_restriction_target",
        ),
        sa.CheckConstraint("group_code IN ('§','A','B','C')", name="ck_travel_restriction_group"),
        sa.CheckConstraint(
            "scope IN ('route_stop','trip_call')", name="ck_travel_restriction_scope"
        ),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_travel_restriction_snapshot"
        ),
        sa.PrimaryKeyConstraint("build_id", "assignment_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "build_job",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_spec_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.SmallInteger(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "state IN ('queued','running','succeeded','failed','cancelled')",
            name="ck_build_job_state",
        ),
        sa.CheckConstraint("priority BETWEEN -32768 AND 32767", name="ck_build_job_priority"),
        sa.ForeignKeyConstraint(
            ["build_spec_sha256"],
            ["control.build_spec.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="control",
    )
    op.create_table(
        "source_config_revision",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name="ck_source_config_sha256"),
        sa.CheckConstraint("schema_version > 0", name="ck_source_config_schema_version"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["control.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "sha256", name="uq_source_config_digest"),
        schema="control",
    )
    op.create_table(
        "source_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("declared_version", sa.Text(), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("manifest_sha256 ~ '^[0-9a-f]{64}$'", name="ck_snapshot_manifest"),
        sa.CheckConstraint("payload_sha256 ~ '^[0-9a-f]{64}$'", name="ck_snapshot_payload"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["control.source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "payload_sha256", name="uq_source_snapshot_payload"),
        schema="control",
    )
    op.create_table(
        "static_build",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("feed_version", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("identity_contract", sa.String(length=32), nullable=False),
        sa.Column("build_spec_sha256", sa.String(length=64), nullable=False),
        sa.Column("build_key_sha256", sa.String(length=64), nullable=False),
        sa.Column("manifest_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_set_sha256", sa.String(length=64), nullable=False),
        sa.Column("overlay_policy_sha256", sa.String(length=64), nullable=False),
        sa.Column("compiler_sha256", sa.String(length=64), nullable=False),
        sa.Column("compiler_identity", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("compiler_options_sha256", sa.String(length=64), nullable=False),
        sa.Column("registry_snapshot_sha256", sa.String(length=64), nullable=True),
        sa.Column("gtfs_sha256", sa.String(length=64), nullable=False),
        sa.Column("serving_sha256", sa.String(length=64), nullable=False),
        sa.Column("netex_mapping_version", sa.String(length=32), nullable=False),
        sa.Column("netex_target_schema", sa.String(length=32), nullable=False),
        sa.Column("netex_extension_version", sa.String(length=32), nullable=False),
        sa.Column("netex_mapping_sha256", sa.String(length=64), nullable=False),
        sa.Column("partitions_attached", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_pruned_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("build_key_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_key"),
        sa.CheckConstraint(
            "compiler_options_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_compiler_options"
        ),
        sa.CheckConstraint("compiler_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_compiler"),
        sa.CheckConstraint("gtfs_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_gtfs"),
        sa.CheckConstraint(
            "identity_contract IN ('provisional-v0','registry-v1')",
            name="ck_static_build_identity_contract",
        ),
        sa.CheckConstraint("manifest_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_manifest"),
        sa.CheckConstraint(
            "netex_mapping_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_netex_mapping"
        ),
        sa.CheckConstraint("overlay_policy_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_policy"),
        sa.CheckConstraint(
            "registry_snapshot_sha256 IS NULL OR registry_snapshot_sha256 ~ '^[0-9a-f]{64}$'",
            name="ck_build_registry_snapshot",
        ),
        sa.CheckConstraint("serving_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_serving"),
        sa.CheckConstraint("source_set_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_sources"),
        sa.CheckConstraint(
            "state IN ('queued','building','loading','ready','active','retired','failed','pruning','pruned')",
            name="ck_static_build_state",
        ),
        sa.ForeignKeyConstraint(
            ["build_spec_sha256"],
            ["control.build_spec.sha256"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("build_key_sha256", name="uq_static_build_key"),
        sa.UniqueConstraint("feed_version", name="uq_static_build_feed_version"),
        schema="control",
    )
    op.create_table(
        "fare_zone",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("fare_system_id", sa.Text(), nullable=False),
        sa.Column("zone_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id", "fare_system_id"],
            ["static.fare_system.build_id", "static.fare_system.fare_system_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "fare_system_id", "zone_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "location_feature",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Text(), nullable=False),
        sa.Column("location_id", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("source_code", sa.String(length=1), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('wheelchair_accessible','refreshments','toilet','accessible_toilet','request_stop','urban_transport_interchange','border_control_only','visually_impaired_accessible','accessibility_terminal','rail_interchange','line_interchange','metro_interchange','ship_terminal','airport_nearby','park_and_ride')",
            name="ck_location_feature_kind",
        ),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_location_feature_snapshot"
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "location_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "feature_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "operational_call",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_journey_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("source_location_id", sa.Text(), nullable=False),
        sa.Column("passenger_service", sa.Boolean(), nullable=False),
        sa.Column("scheduled_arrival", sa.Integer(), nullable=True),
        sa.Column("scheduled_departure", sa.Integer(), nullable=True),
        sa.Column("scheduled_passage", sa.Integer(), nullable=True),
        sa.Column("subsidiary_code", sa.Text(), nullable=True),
        sa.Column("subsidiary_name", sa.Text(), nullable=True),
        sa.Column("active_line_code", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "scheduled_arrival IS NOT NULL OR scheduled_departure IS NOT NULL OR scheduled_passage IS NOT NULL",
            name="ck_operational_call_time",
        ),
        sa.CheckConstraint("sequence > 0", name="ck_operational_call_sequence"),
        sa.ForeignKeyConstraint(
            ["build_id", "source_id", "source_journey_id"],
            [
                "static.operational_journey.build_id",
                "static.operational_journey.source_id",
                "static.operational_journey.source_journey_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "source_id", "source_location_id"],
            [
                "static.operational_location.build_id",
                "static.operational_location.source_id",
                "static.operational_location.source_location_id",
            ],
        ),
        sa.PrimaryKeyConstraint("build_id", "source_id", "source_journey_id", "sequence"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "route",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("agency_id", sa.Text(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("gtfs_route_type", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("long_name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=6), nullable=True),
        sa.Column("text_color", sa.String(length=6), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.CheckConstraint("gtfs_route_type >= 0", name="ck_route_type"),
        sa.ForeignKeyConstraint(
            ["build_id", "agency_id"],
            ["static.agency.build_id", "static.agency.agency_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "route_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "service_exception",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("added", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "service_id"],
            ["static.service_calendar.build_id", "static.service_calendar.service_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "service_id", "service_date"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "shape_point",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("shape_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("distance_traveled", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "distance_traveled IS NULL OR distance_traveled >= 0", name="ck_shape_point_distance"
        ),
        sa.CheckConstraint("sequence >= 0", name="ck_shape_point_sequence"),
        sa.ForeignKeyConstraint(
            ["build_id", "shape_id"],
            ["static.shape.build_id", "static.shape.shape_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "shape_id", "sequence"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "transfer",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("transfer_key", sa.Text(), nullable=False),
        sa.Column("from_location_id", sa.Text(), nullable=False),
        sa.Column("to_location_id", sa.Text(), nullable=False),
        sa.Column("from_route_id", sa.Text(), nullable=True),
        sa.Column("to_route_id", sa.Text(), nullable=True),
        sa.Column("from_trip_id", sa.Text(), nullable=True),
        sa.Column("to_trip_id", sa.Text(), nullable=True),
        sa.Column("transfer_type", sa.SmallInteger(), nullable=False),
        sa.Column("minimum_transfer_time", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["build_id", "from_location_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "to_location_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "transfer_key"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "build_artifact",
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=96), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_sha256"],
            ["control.artifact.sha256"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["control.static_build.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("build_id", "role"),
        schema="control",
    )
    op.create_table(
        "build_diagnostic",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=96), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("blocks_activation", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("severity IN ('info','warning','error')", name="ck_build_diag_severity"),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["control.static_build.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="control",
    )
    op.create_table(
        "build_job_attempt",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "heartbeat_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("log_artifact_sha256", sa.String(length=64), nullable=True),
        sa.CheckConstraint("attempt > 0", name="ck_build_attempt_number"),
        sa.ForeignKeyConstraint(["job_id"], ["control.build_job.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["log_artifact_sha256"],
            ["control.artifact.sha256"],
        ),
        sa.PrimaryKeyConstraint("job_id", "attempt"),
        schema="control",
    )
    op.create_table(
        "build_job_event",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["control.build_job.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="control",
    )
    op.create_table(
        "build_validation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("validator", sa.String(length=96), nullable=False),
        sa.Column("advisory", sa.Boolean(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["control.static_build.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="control",
    )
    op.create_table(
        "publication",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("active_build_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_build_id"],
            ["control.static_build.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
        schema="control",
    )
    op.create_table(
        "source_snapshot_artifact",
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=96), nullable=False),
        sa.Column("artifact_sha256", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_sha256"],
            ["control.artifact.sha256"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["control.source_snapshot.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "role"),
        schema="control",
    )
    op.create_table(
        "static_build_input",
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=96), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["control.static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["control.source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "snapshot_id", "role"),
        schema="control",
    )
    op.create_table(
        "location_zone",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Text(), nullable=False),
        sa.Column("fare_system_id", sa.Text(), nullable=False),
        sa.Column("zone_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "fare_system_id", "zone_id"],
            [
                "static.fare_zone.build_id",
                "static.fare_zone.fare_system_id",
                "static.fare_zone.zone_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "location_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "location_id", "fare_system_id", "zone_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "road_route_key",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("cis_line_id", sa.String(length=6), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.CheckConstraint("cis_line_id ~ '^[0-9]{6}$'", name="ck_road_route_cis_line"),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_road_route_validity"),
        sa.ForeignKeyConstraint(
            ["build_id", "route_id"],
            ["static.route.build_id", "static.route.route_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "cis_line_id", "route_id", "valid_from"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_road_route_key",
        "road_route_key",
        ["build_id", "cis_line_id", "valid_from", "valid_to"],
        unique=False,
        schema="static",
    )
    op.create_table(
        "trip",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.Column("service_id", sa.Text(), nullable=False),
        sa.Column("direction", sa.SmallInteger(), nullable=True),
        sa.Column("headsign", sa.Text(), nullable=True),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("block_key", sa.Text(), nullable=True),
        sa.Column("wheelchair_accessible", sa.SmallInteger(), nullable=True),
        sa.Column("bikes_allowed", sa.SmallInteger(), nullable=True),
        sa.Column("shape_id", sa.Text(), nullable=True),
        sa.CheckConstraint("direction IS NULL OR direction IN (0,1)", name="ck_trip_direction"),
        sa.ForeignKeyConstraint(
            ["build_id", "route_id"],
            ["static.route.build_id", "static.route.route_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "service_id"],
            ["static.service_calendar.build_id", "static.service_calendar.service_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "shape_id"],
            ["static.shape.build_id", "static.shape.shape_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "trip_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "rail_trip_key",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("train_number", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.CheckConstraint("train_number > 0", name="ck_rail_trip_number"),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_rail_trip_validity"),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "train_number", "trip_id", "valid_from"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_rail_trip_key",
        "rail_trip_key",
        ["build_id", "train_number", "valid_from", "valid_to"],
        unique=False,
        schema="static",
    )
    op.create_table(
        "road_trip_key",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("cis_line_id", sa.String(length=6), nullable=False),
        sa.Column("cis_trip_id", sa.BigInteger(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.CheckConstraint("cis_line_id ~ '^[0-9]{6}$'", name="ck_road_trip_cis_line"),
        sa.CheckConstraint("cis_trip_id >= 0", name="ck_road_trip_cis_trip"),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_road_trip_validity"),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "cis_line_id", "cis_trip_id", "trip_id", "valid_from"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_road_trip_key",
        "road_trip_key",
        ["build_id", "cis_line_id", "cis_trip_id", "valid_from", "valid_to"],
        unique=False,
        schema="static",
    )
    op.create_table(
        "route_segment",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("from_sequence", sa.Integer(), nullable=False),
        sa.Column("to_sequence", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=False),
        sa.CheckConstraint("from_sequence > 0", name="ck_route_segment_start"),
        sa.CheckConstraint("to_sequence >= from_sequence", name="ck_route_segment_end"),
        sa.ForeignKeyConstraint(
            ["build_id", "route_id"],
            ["static.route.build_id", "static.route.route_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "trip_id", "from_sequence"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "service_note_assignment",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Text(), nullable=False),
        sa.Column("note_id", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=True),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(scope='route' AND route_id IS NOT NULL AND trip_id IS NULL) OR (scope='trip' AND trip_id IS NOT NULL AND route_id IS NULL)",
            name="ck_service_note_assignment_target",
        ),
        sa.CheckConstraint("scope IN ('route','trip')", name="ck_service_note_assignment_scope"),
        sa.ForeignKeyConstraint(
            ["build_id", "note_id"],
            ["static.service_note.build_id", "static.service_note.note_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "route_id"],
            ["static.route.build_id", "static.route.route_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "assignment_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "source_trip_coverage",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("coverage_id", sa.Text(), nullable=False),
        sa.Column("trip_namespace", sa.String(length=64), nullable=False),
        sa.Column("source_trip_id", sa.Text(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("from_sequence", sa.Integer(), nullable=False),
        sa.Column("to_sequence", sa.Integer(), nullable=False),
        sa.Column("coverage_type", sa.String(length=32), nullable=False),
        sa.Column("system_id", sa.Text(), nullable=True),
        sa.Column("coverage_role", sa.String(length=32), nullable=True),
        sa.CheckConstraint("trip_namespace <> ''", name="ck_source_coverage_trip_namespace"),
        sa.CheckConstraint("from_sequence > 0", name="ck_source_coverage_start"),
        sa.CheckConstraint("to_sequence >= from_sequence", name="ck_source_coverage_end"),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "source_id", "coverage_id", "trip_id", "from_sequence"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "source_trip_map",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("trip_namespace", sa.String(length=64), nullable=False),
        sa.Column("source_trip_id", sa.Text(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("scheduled_start", sa.Integer(), nullable=True),
        sa.Column("scheduled_end", sa.Integer(), nullable=True),
        sa.Column("source_route_id", sa.Text(), nullable=True),
        sa.Column("source_direction_id", sa.Text(), nullable=True),
        sa.Column("source_start_location_id", sa.Text(), nullable=True),
        sa.Column("source_end_location_id", sa.Text(), nullable=True),
        sa.Column("source_block_id", sa.Text(), nullable=True),
        sa.Column("source_run_id", sa.Text(), nullable=True),
        sa.Column("source_duty_id", sa.Text(), nullable=True),
        sa.Column("call_pattern_sha256", sa.String(length=64), nullable=True),
        sa.Column("variant_key", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "call_pattern_sha256 IS NULL OR call_pattern_sha256 ~ '^[0-9a-f]{64}$'",
            name="ck_source_trip_call_pattern",
        ),
        sa.CheckConstraint("trip_namespace <> ''", name="ck_source_trip_namespace"),
        sa.CheckConstraint(
            "scheduled_end IS NULL OR scheduled_end >= 0", name="ck_source_trip_end"
        ),
        sa.CheckConstraint(
            "scheduled_start IS NULL OR scheduled_end IS NULL OR scheduled_end >= scheduled_start",
            name="ck_source_trip_time_order",
        ),
        sa.CheckConstraint(
            "scheduled_start IS NULL OR scheduled_start >= 0", name="ck_source_trip_start"
        ),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_source_trip_validity"),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint(
            "build_id", "source_id", "trip_namespace", "source_trip_id", "trip_id", "valid_from"
        ),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_index(
        "ix_source_trip_resolve",
        "source_trip_map",
        ["build_id", "source_id", "trip_namespace", "source_trip_id", "valid_from", "valid_to"],
        unique=False,
        schema="static",
    )
    op.create_table(
        "trip_call",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Text(), nullable=False),
        sa.Column("passenger_service", sa.Boolean(), nullable=False),
        sa.Column("boarding_point_id", sa.Text(), nullable=True),
        sa.Column("scheduled_arrival", sa.Integer(), nullable=True),
        sa.Column("scheduled_departure", sa.Integer(), nullable=True),
        sa.Column("scheduled_passage", sa.Integer(), nullable=True),
        sa.Column("pickup_type", sa.SmallInteger(), nullable=False),
        sa.Column("dropoff_type", sa.SmallInteger(), nullable=False),
        sa.Column("timepoint", sa.Boolean(), nullable=False),
        sa.Column("stop_headsign", sa.Text(), nullable=True),
        sa.Column("shape_distance_traveled", sa.Float(), nullable=True),
        sa.CheckConstraint("dropoff_type BETWEEN 0 AND 3", name="ck_call_dropoff"),
        sa.CheckConstraint("pickup_type BETWEEN 0 AND 3", name="ck_call_pickup"),
        sa.CheckConstraint(
            "scheduled_arrival IS NULL OR scheduled_arrival >= 0", name="ck_call_arrival"
        ),
        sa.CheckConstraint(
            "scheduled_departure IS NULL OR scheduled_departure >= 0", name="ck_call_departure"
        ),
        sa.CheckConstraint(
            "scheduled_passage IS NULL OR scheduled_passage >= 0", name="ck_call_passage"
        ),
        sa.CheckConstraint("sequence > 0", name="ck_trip_call_sequence"),
        sa.ForeignKeyConstraint(
            ["build_id", "boarding_point_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "location_id"],
            ["static.location.build_id", "static.location.location_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "trip_id", "sequence"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "call_zone",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("fare_system_id", sa.Text(), nullable=False),
        sa.Column("zone_id", sa.Text(), nullable=False),
        sa.Column("source_order", sa.Integer(), nullable=False),
        sa.CheckConstraint("source_order >= 0", name="ck_call_zone_order"),
        sa.ForeignKeyConstraint(
            ["build_id", "fare_system_id", "zone_id"],
            [
                "static.fare_zone.build_id",
                "static.fare_zone.fare_system_id",
                "static.fare_zone.zone_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id", "sequence"],
            ["static.trip_call.build_id", "static.trip_call.trip_id", "static.trip_call.sequence"],
        ),
        sa.PrimaryKeyConstraint("build_id", "trip_id", "sequence", "fare_system_id", "zone_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "connection_claim",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Text(), nullable=False),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("origin_trip_id", sa.Text(), nullable=False),
        sa.Column("origin_sequence", sa.Integer(), nullable=False),
        sa.Column("target_source_route_id", sa.Text(), nullable=True),
        sa.Column("target_source_trip_id", sa.Text(), nullable=True),
        sa.Column("target_source_stop_id", sa.Text(), nullable=True),
        sa.Column("target_source_post_id", sa.Text(), nullable=True),
        sa.Column("target_source_end_stop_id", sa.Text(), nullable=True),
        sa.Column("target_source_end_post_id", sa.Text(), nullable=True),
        sa.Column("wait_minutes", sa.Integer(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("target_public_line", sa.Text(), nullable=True),
        sa.Column("target_destination_text", sa.Text(), nullable=True),
        sa.Column("target_derivation", sa.String(length=16), nullable=False),
        sa.Column("resolution_status", sa.String(length=16), nullable=False),
        sa.Column("target_route_id", sa.Text(), nullable=True),
        sa.Column("target_trip_id", sa.Text(), nullable=True),
        sa.Column("target_location_id", sa.Text(), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "direction IN ('waits_for','connects_to')", name="ck_connection_direction"
        ),
        sa.CheckConstraint(
            "resolution_status IN ('unresolved','pattern','resolved')",
            name="ck_connection_resolution",
        ),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_connection_snapshot"
        ),
        sa.CheckConstraint(
            "target_derivation IN ('none','structured','spec_note')",
            name="ck_connection_target_derivation",
        ),
        sa.CheckConstraint("wait_minutes IS NULL OR wait_minutes >= 0", name="ck_connection_wait"),
        sa.ForeignKeyConstraint(
            ["build_id", "origin_trip_id", "origin_sequence"],
            ["static.trip_call.build_id", "static.trip_call.trip_id", "static.trip_call.sequence"],
        ),
        sa.PrimaryKeyConstraint("build_id", "connection_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "service_feature_assignment",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("feature_id", sa.Text(), nullable=False),
        sa.Column("scope", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("route_id", sa.Text(), nullable=True),
        sa.Column("trip_id", sa.Text(), nullable=True),
        sa.Column("call_sequence", sa.Integer(), nullable=True),
        sa.Column("source_code", sa.String(length=1), nullable=False),
        sa.Column("note_id", sa.Text(), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("source_snapshot_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "(scope='route' AND route_id IS NOT NULL AND trip_id IS NULL AND call_sequence IS NULL) OR (scope='trip' AND route_id IS NULL AND trip_id IS NOT NULL AND call_sequence IS NULL) OR (scope='call' AND route_id IS NULL AND trip_id IS NOT NULL AND call_sequence IS NOT NULL)",
            name="ck_service_feature_target",
        ),
        sa.CheckConstraint(
            "kind IN ('reservation_available','reservation_required','wheelchair_accessible_vehicle','partly_wheelchair_accessible_vehicle','refreshments_on_vehicle','luggage_transport','bicycle_transport','on_request','conditional','self_service_ticketing','integrated_transport','not_stopping','diversion','request_stop','exit_only','boarding_only')",
            name="ck_service_feature_kind",
        ),
        sa.CheckConstraint("scope IN ('route','trip','call')", name="ck_service_feature_scope"),
        sa.CheckConstraint(
            "source_snapshot_sha256 ~ '^[0-9a-f]{64}$'", name="ck_service_feature_snapshot"
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "note_id"],
            ["static.service_note.build_id", "static.service_note.note_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "route_id"],
            ["static.route.build_id", "static.route.route_id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id", "call_sequence"],
            ["static.trip_call.build_id", "static.trip_call.trip_id", "static.trip_call.sequence"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["static.trip.build_id", "static.trip.trip_id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "feature_id"),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    op.create_table(
        "source_call_map",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("trip_namespace", sa.String(length=64), nullable=False),
        sa.Column("source_trip_id", sa.Text(), nullable=False),
        sa.Column("call_namespace", sa.String(length=64), nullable=False),
        sa.Column("source_sequence", sa.Text(), nullable=False),
        sa.Column("trip_id", sa.Text(), nullable=False),
        sa.Column("call_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint("call_namespace <> ''", name="ck_source_call_namespace"),
        sa.CheckConstraint("trip_namespace <> ''", name="ck_source_call_trip_namespace"),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id", "call_sequence"],
            ["static.trip_call.build_id", "static.trip_call.trip_id", "static.trip_call.sequence"],
        ),
        sa.PrimaryKeyConstraint(
            "build_id",
            "source_id",
            "trip_namespace",
            "source_trip_id",
            "call_namespace",
            "source_sequence",
            "trip_id",
            "call_sequence",
        ),
        schema="static",
        postgresql_partition_by="LIST (build_id)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_call_map", schema="static")
    op.drop_table("service_feature_assignment", schema="static")
    op.drop_table("connection_claim", schema="static")
    op.drop_table("call_zone", schema="static")
    op.drop_table("trip_call", schema="static")
    op.drop_index("ix_source_trip_resolve", table_name="source_trip_map", schema="static")
    op.drop_table("source_trip_map", schema="static")
    op.drop_table("source_trip_coverage", schema="static")
    op.drop_table("service_note_assignment", schema="static")
    op.drop_table("route_segment", schema="static")
    op.drop_index("ix_road_trip_key", table_name="road_trip_key", schema="static")
    op.drop_table("road_trip_key", schema="static")
    op.drop_index("ix_rail_trip_key", table_name="rail_trip_key", schema="static")
    op.drop_table("rail_trip_key", schema="static")
    op.drop_table("trip", schema="static")
    op.drop_index("ix_road_route_key", table_name="road_route_key", schema="static")
    op.drop_table("road_route_key", schema="static")
    op.drop_table("location_zone", schema="static")
    op.drop_table("static_build_input", schema="control")
    op.drop_table("source_snapshot_artifact", schema="control")
    op.drop_table("publication", schema="control")
    op.drop_table("build_validation", schema="control")
    op.drop_table("build_job_event", schema="control")
    op.drop_table("build_job_attempt", schema="control")
    op.drop_table("build_diagnostic", schema="control")
    op.drop_table("build_artifact", schema="control")
    op.drop_table("transfer", schema="static")
    op.drop_table("shape_point", schema="static")
    op.drop_table("service_exception", schema="static")
    op.drop_table("route", schema="static")
    op.drop_table("operational_call", schema="static")
    op.drop_table("location_feature", schema="static")
    op.drop_table("fare_zone", schema="static")
    op.drop_table("static_build", schema="control")
    op.drop_table("source_snapshot", schema="control")
    op.drop_table("source_config_revision", schema="control")
    op.drop_table("build_job", schema="control")
    op.drop_table("travel_restriction_assignment", schema="static")
    op.drop_index("ix_source_entity_public", table_name="source_entity_map", schema="static")
    op.drop_table("source_entity_map", schema="static")
    op.drop_index(
        "ix_static_shape_geometry", table_name="shape", schema="static", postgresql_using="gist"
    )
    op.drop_table("shape", schema="static")
    op.drop_table("service_note", schema="static")
    op.drop_table("service_calendar", schema="static")
    op.drop_table("selected_field_provenance", schema="static")
    op.drop_index(
        "ix_operational_location_position",
        table_name="operational_location",
        schema="static",
        postgresql_using="gist",
    )
    op.drop_table("operational_location", schema="static")
    op.drop_table("operational_journey", schema="static")
    op.drop_index(
        "ix_static_location_position",
        table_name="location",
        schema="static",
        postgresql_using="gist",
    )
    op.drop_table("location", schema="static")
    op.drop_table("identifier_alias", schema="static")
    op.drop_table("fare_system", schema="static")
    op.drop_table("agency", schema="static")
    op.drop_table("source", schema="control")
    op.drop_table("build_spec", schema="control")
    op.drop_table("artifact", schema="control")
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA static")
    op.execute("DROP SCHEMA control")
