# ruff: noqa: E501
"""database v1 foundation

Revision ID: 0001
Revises:
Create Date: 2026-08-02 22:51:29.989066
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    for kind in (
        "operator",
        "stop_place",
        "boarding_point",
        "operational_point",
        "route",
        "scheduled_trip",
    ):
        op.execute(f"CREATE SEQUENCE canonical_{kind}_seq MINVALUE 1 MAXVALUE 999999999 NO CYCLE")
    op.create_table(
        "canonical_entity",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("redirect_to_id", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'redirected' AND redirect_to_id IS NOT NULL) OR (status <> 'redirected' AND redirect_to_id IS NULL)",
            name="ck_canonical_entity_redirect_state",
        ),
        sa.CheckConstraint(
            "kind IN ('operator','stop_place','boarding_point','operational_point','route','scheduled_trip')",
            name="ck_canonical_entity_kind",
        ),
        sa.CheckConstraint(
            "status IN ('active','tombstoned','redirected')", name="ck_canonical_entity_status"
        ),
        sa.CheckConstraint(
            "redirect_to_id IS NULL OR redirect_to_id <> id", name="ck_no_self_redirect"
        ),
        sa.ForeignKeyConstraint(["redirect_to_id"], ["canonical_entity.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fare_system",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=96), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("adapter_kind", sa.String(length=32), nullable=False),
        sa.Column("default_domain", sa.String(length=16), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "default_domain IS NULL OR default_domain IN ('surface','heavy_rail')",
            name="ck_source_domain",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "static_build",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=160), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("config_sha256", sa.String(length=64), nullable=False),
        sa.Column("compiler_version", sa.String(length=160), nullable=False),
        sa.Column("output_artifact_key", sa.Text(), nullable=True),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("ready_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payload_pruned_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("config_sha256 ~ '^[0-9a-f]{64}$'", name="ck_build_config_sha256"),
        sa.CheckConstraint(
            "state IN ('building','ready','active','retired','failed','pruning','pruned')",
            name="ck_static_build_state",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "build_diagnostic",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=96), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("blocks_activation", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info','warning','error')", name="ck_build_diagnostic_severity"
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["static_build.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "build_validation",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("validator", sa.String(length=96), nullable=False),
        sa.Column("is_advisory", sa.Boolean(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["static_build.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "canonical_route",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("location_domain", sa.String(length=16), nullable=False),
        sa.CheckConstraint("location_domain IN ('surface','heavy_rail')", name="ck_route_domain"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["canonical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fare_zone_revision",
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("fare_system_id", sa.BigInteger(), nullable=False),
        sa.Column("zone_key", sa.String(length=160), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["fare_system_id"],
            ["fare_system.id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "fare_system_id", "zone_key"),
    )
    op.create_table(
        "identifier_alias",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("identifier_kind", sa.String(length=64), nullable=False),
        sa.Column("observed_value", sa.Text(), nullable=False),
        sa.Column("normalized_value", sa.Text(), nullable=False),
        sa.Column("validity", postgresql.DATERANGE(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        postgresql.ExcludeConstraint(
            (sa.column("source_id"), "="),
            (sa.column("identifier_kind"), "="),
            (sa.column("observed_value"), "="),
            (sa.column("validity"), "&&"),
            using="gist",
            name="ex_identifier_alias_no_overlap",
        ),
        sa.CheckConstraint("NOT isempty(validity)", name="ck_identifier_alias_nonempty"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operational_point",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("location_domain", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "location_domain IN ('surface','heavy_rail')", name="ck_operational_point_domain"
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["canonical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operator",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["canonical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publication",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("active_build_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["active_build_id"],
            ["static_build.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "scheduled_trip",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("location_domain", sa.String(length=16), nullable=False),
        sa.CheckConstraint("location_domain IN ('surface','heavy_rail')", name="ck_trip_domain"),
        sa.ForeignKeyConstraint(
            ["id"],
            ["canonical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_calendar",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=False),
        sa.Column("weekday_mask", sa.Integer(), nullable=False),
        sa.Column("source_service_id", sa.Text(), nullable=True),
        sa.CheckConstraint("valid_to >= valid_from", name="ck_calendar_validity"),
        sa.CheckConstraint("weekday_mask BETWEEN 0 AND 127", name="ck_weekday_mask"),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("build_id", "id", name="uq_calendar_build_id"),
    )
    op.create_table(
        "source_snapshot",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("declared_version", sa.Text(), nullable=True),
        sa.Column("artifact_key", sa.Text(), nullable=False),
        sa.Column("manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "artifact_key !~ '^(?:[A-Za-z]:|/|\\\\)'", name="ck_snapshot_relative_key"
        ),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name="ck_snapshot_sha256"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "content_sha256", name="uq_source_snapshot_content"),
    )
    op.create_table(
        "stop_place",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("location_domain", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "location_domain IN ('surface','heavy_rail')", name="ck_stop_place_domain"
        ),
        sa.ForeignKeyConstraint(
            ["id"],
            ["canonical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "boarding_point",
        sa.Column("id", sa.String(length=10), nullable=False),
        sa.Column("stop_place_id", sa.String(length=10), nullable=False),
        sa.Column("is_unspecified", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["canonical_entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stop_place_id"],
            ["stop_place.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_boarding_point_unspecified_per_place",
        "boarding_point",
        ["stop_place_id"],
        unique=True,
        postgresql_where=sa.text("is_unspecified"),
    )
    op.create_table(
        "canonical_rail_trip_key",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("train_number", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.String(length=10), nullable=False),
        sa.Column("validity", postgresql.DATERANGE(), nullable=False),
        sa.Column("asserting_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("NOT isempty(validity)", name="ck_rail_trip_key_nonempty"),
        sa.CheckConstraint("train_number > 0", name="ck_rail_trip_train_number"),
        sa.ForeignKeyConstraint(
            ["asserting_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rail_trip_train_number", "canonical_rail_trip_key", ["train_number"], unique=False
    )
    op.create_table(
        "canonical_road_route_key",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cis_line_id", sa.String(length=6), nullable=False),
        sa.Column("route_id", sa.String(length=10), nullable=False),
        sa.Column("validity", postgresql.DATERANGE(), nullable=False),
        sa.Column("asserting_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("cis_line_id ~ '^[0-9]{6}$'", name="ck_road_route_cis_line"),
        sa.CheckConstraint("NOT isempty(validity)", name="ck_road_route_key_nonempty"),
        sa.ForeignKeyConstraint(
            ["asserting_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["canonical_route.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_road_route_cis_line", "canonical_road_route_key", ["cis_line_id"], unique=False
    )
    op.create_table(
        "canonical_road_trip_key",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cis_line_id", sa.String(length=6), nullable=False),
        sa.Column("cis_trip_id", sa.BigInteger(), nullable=False),
        sa.Column("trip_id", sa.String(length=10), nullable=False),
        sa.Column("validity", postgresql.DATERANGE(), nullable=False),
        sa.Column("asserting_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint("cis_line_id ~ '^[0-9]{6}$'", name="ck_road_trip_cis_line"),
        sa.CheckConstraint("NOT isempty(validity)", name="ck_road_trip_key_nonempty"),
        sa.CheckConstraint("cis_trip_id >= 0", name="ck_road_trip_cis_trip"),
        sa.ForeignKeyConstraint(
            ["asserting_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_road_trip_cis_pair",
        "canonical_road_trip_key",
        ["cis_line_id", "cis_trip_id"],
        unique=False,
    )
    op.create_table(
        "external_identifier",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("namespace", sa.String(length=64), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("canonical_entity_id", sa.String(length=10), nullable=False),
        sa.Column("validity", postgresql.DATERANGE(), nullable=False),
        sa.Column("asserting_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=160), nullable=True),
        sa.CheckConstraint("NOT isempty(validity)", name="ck_external_identifier_nonempty"),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name="ck_external_identifier_confidence"),
        sa.ForeignKeyConstraint(
            ["asserting_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"],
            ["canonical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_external_identifier_lookup", "external_identifier", ["namespace", "value"], unique=False
    )
    op.create_table(
        "identity_diagnostic",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("entity_kind", sa.String(length=32), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("error_category", sa.String(length=64), nullable=False),
        sa.Column("review_state", sa.String(length=24), nullable=False),
        sa.Column("candidate_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=160), nullable=True),
        sa.CheckConstraint(
            "review_state IN ('unresolved','ambiguous','accepted','manually_resolved')",
            name="ck_diagnostic_review_state",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "operational_point_revision",
        sa.Column("operational_point_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("public_code", sa.Text(), nullable=True),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["operational_point_id"],
            ["operational_point.id"],
        ),
        sa.PrimaryKeyConstraint("operational_point_id", "build_id"),
    )
    op.create_table(
        "operator_revision",
        sa.Column("operator_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("fare_url", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.PrimaryKeyConstraint("operator_id", "build_id"),
    )
    op.create_table(
        "route_revision",
        sa.Column("route_id", sa.String(length=10), nullable=False),
        sa.Column("operator_id", sa.String(length=10), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("gtfs_route_type", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("long_name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("color", sa.String(length=6), nullable=True),
        sa.Column("text_color", sa.String(length=6), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operator.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["canonical_route.id"],
        ),
        sa.PrimaryKeyConstraint("route_id", "build_id"),
    )
    op.create_table(
        "selected_field_provenance",
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("field_name", sa.String(length=96), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("source_object_kind", sa.String(length=32), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.Column("selection_rule", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "object_type", "object_key", "field_name"),
    )
    op.create_table(
        "service_exception",
        sa.Column("calendar_id", sa.BigInteger(), nullable=False),
        sa.Column("service_date", sa.Date(), nullable=False),
        sa.Column("added", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["calendar_id"], ["service_calendar.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("calendar_id", "service_date"),
    )
    op.create_table(
        "shape",
        sa.Column("shape_id", sa.String(length=160), nullable=False),
        sa.Column("generation_method", sa.String(length=32), nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("shape_id", "build_id"),
    )
    op.create_table(
        "source_binding",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("entity_kind", sa.String(length=32), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.Column("location_domain", sa.String(length=16), nullable=True),
        sa.Column("canonical_entity_id", sa.String(length=10), nullable=False),
        sa.Column("validity", postgresql.DATERANGE(), nullable=False),
        sa.Column("match_method", sa.String(length=64), nullable=False),
        sa.Column("match_confidence", sa.Float(), nullable=False),
        sa.Column("review_state", sa.String(length=24), nullable=False),
        sa.Column("first_seen_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("last_seen_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=160), nullable=True),
        postgresql.ExcludeConstraint(
            (sa.column("source_id"), "="),
            (sa.column("entity_kind"), "="),
            (sa.column("source_object_id"), "="),
            (sa.column("validity"), "&&"),
            using="gist",
            name="ex_source_binding_no_overlap",
        ),
        sa.CheckConstraint(
            "entity_kind IN ('operator','stop_place','boarding_point','operational_point','route','scheduled_trip')",
            name="ck_source_binding_kind",
        ),
        sa.CheckConstraint(
            "location_domain IS NULL OR location_domain IN ('surface','heavy_rail')",
            name="ck_source_binding_domain",
        ),
        sa.CheckConstraint(
            "review_state IN ('unresolved','ambiguous','accepted','manually_resolved')",
            name="ck_binding_review_state",
        ),
        sa.CheckConstraint("NOT isempty(validity)", name="ck_source_binding_nonempty"),
        sa.CheckConstraint("match_confidence BETWEEN 0 AND 1", name="ck_source_binding_confidence"),
        sa.ForeignKeyConstraint(
            ["canonical_entity_id"],
            ["canonical_entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_seen_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["last_seen_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["source.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_object",
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("entity_kind", sa.String(length=32), nullable=False),
        sa.Column("source_object_id", sa.Text(), nullable=False),
        sa.Column("location_domain", sa.String(length=16), nullable=True),
        sa.Column("record_locator", sa.Text(), nullable=False),
        sa.Column("natural_key_hash", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "entity_kind IN ('operator','stop_place','boarding_point','operational_point','route','scheduled_trip')",
            name="ck_source_object_kind",
        ),
        sa.CheckConstraint(
            "location_domain IS NULL OR location_domain IN ('surface','heavy_rail')",
            name="ck_source_object_domain",
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["source_snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("snapshot_id", "entity_kind", "source_object_id"),
    )
    op.create_table(
        "source_snapshot_artifact",
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("logical_role", sa.String(length=96), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=160), nullable=True),
        sa.CheckConstraint("content_sha256 ~ '^[0-9a-f]{64}$'", name="ck_artifact_sha256"),
        sa.CheckConstraint(
            "storage_key !~ '^(?:[A-Za-z]:|/|\\\\)'", name="ck_artifact_relative_key"
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_artifact_size"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["source_snapshot.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("snapshot_id", "logical_role"),
    )
    op.create_table(
        "static_build_input",
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=96), nullable=False),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "snapshot_id", "role"),
    )
    op.create_table(
        "stop_place_revision",
        sa.Column("stop_place_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("public_code", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.Column("wheelchair_boarding", sa.SmallInteger(), nullable=True),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["stop_place_id"],
            ["stop_place.id"],
        ),
        sa.PrimaryKeyConstraint("stop_place_id", "build_id"),
    )
    op.create_table(
        "stop_zone_assignment",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("stop_place_id", sa.String(length=10), nullable=False),
        sa.Column("fare_system_id", sa.Integer(), nullable=False),
        sa.Column("zone_key", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "fare_system_id", "zone_key"],
            [
                "fare_zone_revision.build_id",
                "fare_zone_revision.fare_system_id",
                "fare_zone_revision.zone_key",
            ],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stop_place_id"],
            ["stop_place.id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "stop_place_id", "fare_system_id", "zone_key"),
    )
    op.create_table(
        "trip_instance",
        sa.Column("trip_id", sa.String(length=10), nullable=False),
        sa.Column("operating_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.PrimaryKeyConstraint("trip_id", "operating_date"),
    )
    op.create_table(
        "boarding_point_revision",
        sa.Column("boarding_point_id", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("public_code", sa.Text(), nullable=True),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("wheelchair_boarding", sa.SmallInteger(), nullable=True),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["boarding_point_id"],
            ["boarding_point.id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("boarding_point_id", "build_id"),
    )
    op.create_table(
        "shape_point",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("shape_id", sa.String(length=160), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "position",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("distance_traveled", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "distance_traveled IS NULL OR distance_traveled >= 0", name="ck_shape_point_distance"
        ),
        sa.CheckConstraint("sequence >= 0", name="ck_shape_point_sequence"),
        sa.ForeignKeyConstraint(
            ["build_id", "shape_id"], ["shape.build_id", "shape.shape_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("build_id", "shape_id", "sequence"),
    )
    op.create_table(
        "transfer_revision",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("from_boarding_point_id", sa.String(length=10), nullable=False),
        sa.Column("to_boarding_point_id", sa.String(length=10), nullable=False),
        sa.Column("from_route_id", sa.String(length=10), nullable=True),
        sa.Column("to_route_id", sa.String(length=10), nullable=True),
        sa.Column("from_trip_id", sa.String(length=10), nullable=True),
        sa.Column("to_trip_id", sa.String(length=10), nullable=True),
        sa.Column("transfer_type", sa.SmallInteger(), nullable=False),
        sa.Column("minimum_transfer_time", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["from_boarding_point_id"],
            ["boarding_point.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_route_id"],
            ["canonical_route.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_boarding_point_id"],
            ["boarding_point.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_route_id"],
            ["canonical_route.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trip_revision",
        sa.Column("trip_id", sa.String(length=10), nullable=False),
        sa.Column("route_id", sa.String(length=10), nullable=False),
        sa.Column("calendar_id", sa.BigInteger(), nullable=False),
        sa.Column("direction", sa.SmallInteger(), nullable=True),
        sa.Column("headsign", sa.Text(), nullable=True),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("block_key", sa.Text(), nullable=True),
        sa.Column("wheelchair_accessible", sa.SmallInteger(), nullable=True),
        sa.Column("bikes_allowed", sa.SmallInteger(), nullable=True),
        sa.Column("shape_id", sa.String(length=160), nullable=True),
        sa.Column("build_id", sa.BigInteger(), nullable=False),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint("direction IS NULL OR direction IN (0,1)", name="ck_trip_direction"),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "shape_id"],
            ["shape.build_id", "shape.shape_id"],
        ),
        sa.ForeignKeyConstraint(["build_id"], ["static_build.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["calendar_id"],
            ["service_calendar.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["canonical_route.id"],
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["scheduled_trip.id"],
        ),
        sa.PrimaryKeyConstraint("trip_id", "build_id"),
    )
    op.create_table(
        "trip_call_revision",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.String(length=10), nullable=False),
        sa.Column("passenger_service", sa.Boolean(), nullable=False),
        sa.Column("scheduled_boarding_point_id", sa.String(length=10), nullable=True),
        sa.Column("scheduled_arrival", sa.Integer(), nullable=True),
        sa.Column("scheduled_departure", sa.Integer(), nullable=True),
        sa.Column("scheduled_passage", sa.Integer(), nullable=True),
        sa.Column("pickup_type", sa.SmallInteger(), nullable=False),
        sa.Column("dropoff_type", sa.SmallInteger(), nullable=False),
        sa.Column("timepoint", sa.Boolean(), nullable=False),
        sa.Column("stop_headsign", sa.Text(), nullable=True),
        sa.Column("shape_distance_traveled", sa.Float(), nullable=True),
        sa.Column("base_snapshot_id", sa.BigInteger(), nullable=True),
        sa.Column("base_object_kind", sa.String(length=32), nullable=True),
        sa.Column("base_object_id", sa.Text(), nullable=True),
        sa.Column("extensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "(passenger_service AND scheduled_boarding_point_id IS NOT NULL AND scheduled_passage IS NULL) OR (NOT passenger_service AND scheduled_boarding_point_id IS NULL AND scheduled_arrival IS NULL AND scheduled_departure IS NULL AND pickup_type = 1 AND dropoff_type = 1)",
            name="ck_trip_call_shape",
        ),
        sa.CheckConstraint("dropoff_type BETWEEN 0 AND 3", name="ck_call_dropoff"),
        sa.CheckConstraint("pickup_type BETWEEN 0 AND 3", name="ck_call_pickup"),
        sa.CheckConstraint(
            "scheduled_arrival IS NULL OR scheduled_arrival >= 0", name="ck_call_arrival"
        ),
        sa.CheckConstraint(
            "scheduled_departure IS NULL OR scheduled_departure >= 0", name="ck_call_departure"
        ),
        sa.CheckConstraint(
            "scheduled_passage IS NULL OR scheduled_passage >= 0", name="ck_call_passage"
        ),
        sa.CheckConstraint("sequence > 0", name="ck_trip_call_sequence"),
        sa.ForeignKeyConstraint(
            ["base_snapshot_id"],
            ["source_snapshot.id"],
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id"],
            ["trip_revision.build_id", "trip_revision.trip_id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["canonical_entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_boarding_point_id"],
            ["boarding_point.id"],
        ),
        sa.PrimaryKeyConstraint("build_id", "trip_id", "sequence"),
    )
    op.create_table(
        "trip_call_zone_assignment",
        sa.Column("build_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("fare_system_id", sa.Integer(), nullable=False),
        sa.Column("zone_key", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id", "fare_system_id", "zone_key"],
            [
                "fare_zone_revision.build_id",
                "fare_zone_revision.fare_system_id",
                "fare_zone_revision.zone_key",
            ],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["build_id", "trip_id", "sequence"],
            [
                "trip_call_revision.build_id",
                "trip_call_revision.trip_id",
                "trip_call_revision.sequence",
            ],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("build_id", "trip_id", "sequence", "fare_system_id", "zone_key"),
    )
    _install_v1_behavior()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _remove_v1_behavior()
    op.drop_table("trip_call_zone_assignment")
    op.drop_table("trip_call_revision")
    op.drop_table("trip_revision")
    op.drop_table("transfer_revision")
    op.drop_table("shape_point")
    op.drop_table("boarding_point_revision")
    op.drop_table("trip_instance")
    op.drop_table("stop_zone_assignment")
    op.drop_table("stop_place_revision")
    op.drop_table("static_build_input")
    op.drop_table("source_snapshot_artifact")
    op.drop_table("source_object")
    op.drop_table("source_binding")
    op.drop_table("shape")
    op.drop_table("service_exception")
    op.drop_table("selected_field_provenance")
    op.drop_table("route_revision")
    op.drop_table("operator_revision")
    op.drop_table("operational_point_revision")
    op.drop_table("identity_diagnostic")
    op.drop_index("ix_external_identifier_lookup", table_name="external_identifier")
    op.drop_table("external_identifier")
    op.drop_index("ix_road_trip_cis_pair", table_name="canonical_road_trip_key")
    op.drop_table("canonical_road_trip_key")
    op.drop_index("ix_road_route_cis_line", table_name="canonical_road_route_key")
    op.drop_table("canonical_road_route_key")
    op.drop_index("ix_rail_trip_train_number", table_name="canonical_rail_trip_key")
    op.drop_table("canonical_rail_trip_key")
    op.drop_index(
        "uq_boarding_point_unspecified_per_place",
        table_name="boarding_point",
        postgresql_where=sa.text("is_unspecified"),
    )
    op.drop_table("boarding_point")
    op.drop_table("stop_place")
    op.drop_table("source_snapshot")
    op.drop_table("service_calendar")
    op.drop_table("scheduled_trip")
    op.drop_table("publication")
    op.drop_table("operator")
    op.drop_table("operational_point")
    op.drop_table("identifier_alias")
    op.drop_table("fare_zone_revision")
    op.drop_table("canonical_route")
    op.drop_table("build_validation")
    op.drop_table("build_diagnostic")
    op.drop_table("static_build")
    op.drop_table("source")
    op.drop_table("fare_system")
    op.drop_table("canonical_entity")
    for kind in (
        "scheduled_trip",
        "route",
        "operational_point",
        "boarding_point",
        "stop_place",
        "operator",
    ):
        op.execute(f"DROP SEQUENCE IF EXISTS canonical_{kind}_seq")
    # ### end Alembic commands ###


def _install_v1_behavior() -> None:
    op.execute(
        """
        CREATE FUNCTION validate_canonical_id_kind() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE expected_prefix text;
        BEGIN
            expected_prefix := CASE NEW.kind
                WHEN 'operator' THEN 'C' WHEN 'stop_place' THEN 'S'
                WHEN 'boarding_point' THEN 'P' WHEN 'operational_point' THEN 'O'
                WHEN 'route' THEN 'R' WHEN 'scheduled_trip' THEN 'T'
            END;
            IF expected_prefix IS NULL OR left(NEW.id, 1) <> expected_prefix
               OR NEW.id !~ '^[CSPORT][0-9]{9}$' OR right(NEW.id, 9)::bigint = 0 THEN
                RAISE EXCEPTION 'canonical ID % does not match kind %', NEW.id, NEW.kind;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER canonical_id_kind BEFORE INSERT OR UPDATE ON canonical_entity "
        "FOR EACH ROW EXECUTE FUNCTION validate_canonical_id_kind()"
    )
    op.execute(
        """
        CREATE FUNCTION validate_canonical_child_kind() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE actual_kind text;
        BEGIN
            SELECT kind INTO actual_kind FROM canonical_entity WHERE id = NEW.id;
            IF actual_kind IS DISTINCT FROM TG_ARGV[0] THEN
                RAISE EXCEPTION 'canonical child % must have kind %, got %',
                    NEW.id, TG_ARGV[0], actual_kind;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    for table, kind in {
        "operator": "operator",
        "stop_place": "stop_place",
        "boarding_point": "boarding_point",
        "operational_point": "operational_point",
        "canonical_route": "route",
        "scheduled_trip": "scheduled_trip",
    }.items():
        op.execute(
            f"CREATE TRIGGER {table}_kind BEFORE INSERT OR UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION validate_canonical_child_kind('{kind}')"
        )

    op.execute(
        """
        CREATE FUNCTION canonical_entity_domain(entity_id text) RETURNS text
        LANGUAGE sql STABLE AS $$
            SELECT location_domain FROM stop_place WHERE id = entity_id
            UNION ALL SELECT location_domain FROM operational_point WHERE id = entity_id
            UNION ALL SELECT location_domain FROM canonical_route WHERE id = entity_id
            UNION ALL SELECT location_domain FROM scheduled_trip WHERE id = entity_id
            LIMIT 1
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_source_binding_target() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE target_domain text; DECLARE target_kind text;
        BEGIN
            SELECT kind INTO target_kind FROM canonical_entity WHERE id = NEW.canonical_entity_id;
            target_domain := canonical_entity_domain(NEW.canonical_entity_id);
            IF target_kind IS DISTINCT FROM NEW.entity_kind THEN
                RAISE EXCEPTION 'source binding kind % does not match canonical kind %',
                    NEW.entity_kind, target_kind;
            END IF;
            IF NEW.location_domain IS DISTINCT FROM target_domain
               AND (NEW.location_domain IS NOT NULL OR target_domain IS NOT NULL) THEN
                RAISE EXCEPTION 'source binding domain % does not match canonical domain %',
                    NEW.location_domain, target_domain;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER source_binding_target BEFORE INSERT OR UPDATE ON source_binding "
        "FOR EACH ROW EXECUTE FUNCTION validate_source_binding_target()"
    )
    op.execute(
        """
        CREATE FUNCTION validate_hot_identity_domain() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE actual_domain text; DECLARE wanted_domain text;
        BEGIN
            wanted_domain := CASE WHEN TG_TABLE_NAME = 'canonical_rail_trip_key'
                THEN 'heavy_rail' ELSE 'surface' END;
            IF TG_TABLE_NAME = 'canonical_road_route_key' THEN
                actual_domain := canonical_entity_domain(NEW.route_id);
            ELSE
                actual_domain := canonical_entity_domain(NEW.trip_id);
            END IF;
            IF actual_domain IS DISTINCT FROM wanted_domain THEN
                RAISE EXCEPTION '% requires domain %, got %', TG_TABLE_NAME, wanted_domain, actual_domain;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    for table in ("canonical_road_route_key", "canonical_road_trip_key", "canonical_rail_trip_key"):
        op.execute(
            f"CREATE TRIGGER {table}_domain BEFORE INSERT OR UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION validate_hot_identity_domain()"
        )
    op.execute(
        """
        CREATE FUNCTION validate_schedule_revision_domain() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE left_domain text; DECLARE right_domain text;
        BEGIN
            IF TG_TABLE_NAME = 'route_revision' THEN
                left_domain := canonical_entity_domain(NEW.route_id);
                IF (left_domain = 'heavy_rail') IS DISTINCT FROM (NEW.mode = 'rail') THEN
                    RAISE EXCEPTION 'route mode and domain disagree';
                END IF;
            ELSE
                left_domain := canonical_entity_domain(NEW.trip_id);
                right_domain := canonical_entity_domain(NEW.route_id);
                IF left_domain IS DISTINCT FROM right_domain THEN
                    RAISE EXCEPTION 'trip and route domains differ';
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM service_calendar
                    WHERE id = NEW.calendar_id AND build_id = NEW.build_id
                ) THEN
                    RAISE EXCEPTION 'trip calendar belongs to another build';
                END IF;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    for table in ("route_revision", "trip_revision"):
        op.execute(
            f"CREATE TRIGGER {table}_domain BEFORE INSERT OR UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION validate_schedule_revision_domain()"
        )
    op.execute(
        """
        CREATE FUNCTION validate_trip_call_revision() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE trip_domain text; DECLARE location_domain text;
        DECLARE location_kind text; DECLARE boarding_parent text;
        BEGIN
            trip_domain := canonical_entity_domain(NEW.trip_id);
            SELECT kind, canonical_entity_domain(NEW.location_id)
              INTO location_kind, location_domain
              FROM canonical_entity WHERE id = NEW.location_id;
            IF trip_domain IS DISTINCT FROM location_domain THEN
                RAISE EXCEPTION 'trip and call location domains differ';
            END IF;
            IF NEW.passenger_service THEN
                IF location_kind <> 'stop_place' THEN
                    RAISE EXCEPTION 'passenger call location must be a stop place';
                END IF;
                SELECT stop_place_id INTO boarding_parent FROM boarding_point
                  WHERE id = NEW.scheduled_boarding_point_id;
                IF boarding_parent IS DISTINCT FROM NEW.location_id THEN
                    RAISE EXCEPTION 'boarding point must be a child of the call stop place';
                END IF;
            ELSIF location_kind <> 'operational_point' THEN
                RAISE EXCEPTION 'operational call location must be an operational point';
            END IF;
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER trip_call_revision_shape BEFORE INSERT OR UPDATE ON trip_call_revision "
        "FOR EACH ROW EXECUTE FUNCTION validate_trip_call_revision()"
    )

    op.execute(
        """
        CREATE FUNCTION validate_build_payload_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE old_build_id bigint; DECLARE new_build_id bigint;
        DECLARE old_build_state text; DECLARE new_build_state text;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                old_build_id := OLD.build_id;
                SELECT state INTO old_build_state FROM static_build WHERE id = old_build_id;
                IF old_build_state NOT IN ('building', 'pruning') THEN
                    RAISE EXCEPTION 'build % payload is immutable in state %',
                        old_build_id, old_build_state;
                END IF;
                RETURN OLD;
            END IF;
            new_build_id := NEW.build_id;
            SELECT state INTO new_build_state FROM static_build WHERE id = new_build_id;
            IF TG_OP = 'UPDATE' THEN
                old_build_id := OLD.build_id;
                SELECT state INTO old_build_state FROM static_build WHERE id = old_build_id;
                IF old_build_state <> 'building' THEN
                    RAISE EXCEPTION 'build % payload is immutable in state %',
                        old_build_id, old_build_state;
                END IF;
            END IF;
            IF new_build_state <> 'building' THEN
                RAISE EXCEPTION 'build % payload is immutable in state %',
                    new_build_id, new_build_state;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    payload_tables = (
        "static_build_input",
        "operator_revision",
        "stop_place_revision",
        "boarding_point_revision",
        "operational_point_revision",
        "route_revision",
        "service_calendar",
        "shape",
        "shape_point",
        "trip_revision",
        "trip_call_revision",
        "transfer_revision",
        "fare_zone_revision",
        "stop_zone_assignment",
        "trip_call_zone_assignment",
        "selected_field_provenance",
    )
    for table in payload_tables:
        op.execute(
            f"CREATE TRIGGER {table}_immutable BEFORE INSERT OR UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION validate_build_payload_mutation()"
        )
    op.execute(
        """
        CREATE FUNCTION validate_service_exception_mutation() RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE old_calendar_id bigint; DECLARE new_calendar_id bigint;
        DECLARE old_build_id bigint; DECLARE new_build_id bigint;
        DECLARE old_build_state text; DECLARE new_build_state text;
        BEGIN
            IF TG_OP = 'DELETE' THEN
                old_calendar_id := OLD.calendar_id;
                SELECT b.id, b.state INTO old_build_id, old_build_state
                  FROM service_calendar c JOIN static_build b ON b.id = c.build_id
                  WHERE c.id = old_calendar_id;
                IF old_build_state NOT IN ('building', 'pruning') THEN
                    RAISE EXCEPTION 'build % calendar payload is immutable in state %',
                        old_build_id, old_build_state;
                END IF;
                RETURN OLD;
            END IF;
            new_calendar_id := NEW.calendar_id;
            SELECT b.id, b.state INTO new_build_id, new_build_state
              FROM service_calendar c JOIN static_build b ON b.id = c.build_id
              WHERE c.id = new_calendar_id;
            IF TG_OP = 'UPDATE' THEN
                old_calendar_id := OLD.calendar_id;
                SELECT b.id, b.state INTO old_build_id, old_build_state
                  FROM service_calendar c JOIN static_build b ON b.id = c.build_id
                  WHERE c.id = old_calendar_id;
                IF old_build_state <> 'building' THEN
                    RAISE EXCEPTION 'build % calendar payload is immutable in state %',
                        old_build_id, old_build_state;
                END IF;
            END IF;
            IF new_build_state <> 'building' THEN
                RAISE EXCEPTION 'build % calendar payload is immutable in state %',
                    new_build_id, new_build_state;
            END IF;
            RETURN NEW;
        END $$
        """
    )
    op.execute(
        "CREATE TRIGGER service_exception_immutable BEFORE INSERT OR UPDATE OR DELETE "
        "ON service_exception FOR EACH ROW EXECUTE FUNCTION validate_service_exception_mutation()"
    )

    op.execute(
        """
        CREATE FUNCTION valid_namespaced_extensions(value jsonb) RETURNS boolean
        LANGUAGE sql IMMUTABLE AS $$
            SELECT jsonb_typeof(value) = 'object' AND NOT EXISTS (
                SELECT 1 FROM jsonb_object_keys(value) key
                WHERE key !~ ('^[a-z][a-z0-9_-]*' || ':' || 'v[1-9][0-9]*$')
            )
        $$
        """
    )
    op.execute(
        """
        CREATE FUNCTION validate_revision_provenance() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
            IF NOT valid_namespaced_extensions(NEW.extensions) THEN
                RAISE EXCEPTION 'extension keys must be schema-versioned namespaces';
            END IF;
            IF (NEW.base_snapshot_id IS NULL)::int
               + (NEW.base_object_kind IS NULL)::int
               + (NEW.base_object_id IS NULL)::int NOT IN (0, 3) THEN
                RAISE EXCEPTION 'base source provenance must be entirely present or absent';
            END IF;
            IF NEW.base_snapshot_id IS NOT NULL AND NOT EXISTS (
                SELECT 1 FROM source_object WHERE snapshot_id = NEW.base_snapshot_id
                  AND entity_kind = NEW.base_object_kind
                  AND source_object_id = NEW.base_object_id
            ) THEN
                RAISE EXCEPTION 'base source object does not exist';
            END IF;
            RETURN NEW;
        END $$
        """
    )
    for table in (
        "operator_revision",
        "stop_place_revision",
        "boarding_point_revision",
        "operational_point_revision",
        "route_revision",
        "shape",
        "trip_revision",
        "trip_call_revision",
    ):
        op.execute(
            f"CREATE TRIGGER {table}_provenance BEFORE INSERT OR UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION validate_revision_provenance()"
        )
    op.execute(
        "ALTER TABLE fare_zone_revision ADD CONSTRAINT ck_fare_zone_extensions "
        "CHECK (valid_namespaced_extensions(extensions))"
    )

    source = sa.table(
        "source",
        sa.column("id", sa.String),
        sa.column("display_name", sa.String),
        sa.column("adapter_kind", sa.String),
        sa.column("default_domain", sa.String),
        sa.column("timezone", sa.String),
        sa.column("active", sa.Boolean),
    )
    op.bulk_insert(
        source,
        [
            {
                "id": "national-jdf",
                "display_name": "National JDF",
                "adapter_kind": "jdf",
                "default_domain": "surface",
                "timezone": "Europe/Prague",
                "active": True,
            },
            {
                "id": "national-czptt",
                "display_name": "National CZPTT",
                "adapter_kind": "czptt",
                "default_domain": "heavy_rail",
                "timezone": "Europe/Prague",
                "active": True,
            },
            {
                "id": "pid",
                "display_name": "PID",
                "adapter_kind": "gtfs",
                "default_domain": None,
                "timezone": "Europe/Prague",
                "active": True,
            },
            {
                "id": "duk",
                "display_name": "DÚK",
                "adapter_kind": "custom_realtime",
                "default_domain": "surface",
                "timezone": "Europe/Prague",
                "active": True,
            },
            {
                "id": "cis-authority-mock",
                "display_name": "Synthetic CIS authority",
                "adapter_kind": "fixture_authority",
                "default_domain": "surface",
                "timezone": "Europe/Prague",
                "active": True,
            },
        ],
    )


def _remove_v1_behavior() -> None:
    op.execute("DROP FUNCTION IF EXISTS validate_revision_provenance() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS valid_namespaced_extensions(jsonb) CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_service_exception_mutation() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_build_payload_mutation() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_trip_call_revision() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_schedule_revision_domain() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_hot_identity_domain() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_source_binding_target() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS canonical_entity_domain(text) CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_canonical_child_kind() CASCADE")
    op.execute("DROP FUNCTION IF EXISTS validate_canonical_id_kind() CASCADE")
