-- Generated by `python -m obehy.release.ddl` from serving contract 5.0. Do not edit.

CREATE TABLE static.agency (
    load_id integer NOT NULL,
    agency_id text NOT NULL,
    name text NOT NULL,
    url text,
    timezone text NOT NULL,
    language text,
    phone text,
    fare_url text,
    email text,
    PRIMARY KEY (load_id, agency_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.location (
    load_id integer NOT NULL,
    location_id text NOT NULL,
    kind text NOT NULL,
    domain text NOT NULL,
    parent_location_id text,
    name text NOT NULL,
    public_code text,
    description text,
    municipality_name text,
    district_name text,
    district_code text,
    nearby_place text,
    country_code text,
    coordinate_precision text NOT NULL,
    coordinate_source text,
    longitude double precision,
    latitude double precision,
    url text,
    timezone text,
    wheelchair_boarding smallint,
    geom geometry(Point, 4326) GENERATED ALWAYS AS (CASE WHEN longitude IS NOT NULL AND latitude IS NOT NULL THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) END) STORED,
    PRIMARY KEY (load_id, location_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.route (
    load_id integer NOT NULL,
    route_id text NOT NULL,
    agency_id text NOT NULL,
    mode text NOT NULL,
    gtfs_route_type integer NOT NULL,
    short_name text,
    long_name text,
    description text,
    url text,
    color text,
    text_color text,
    sort_order integer,
    timetable_kind text NOT NULL,
    PRIMARY KEY (load_id, route_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.service_calendar (
    load_id integer NOT NULL,
    service_id text NOT NULL,
    valid_from date NOT NULL,
    valid_to date NOT NULL,
    weekday_mask smallint NOT NULL,
    PRIMARY KEY (load_id, service_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.service_exception (
    load_id integer NOT NULL,
    service_id text NOT NULL,
    service_date date NOT NULL,
    added boolean NOT NULL,
    PRIMARY KEY (load_id, service_id, service_date)
) PARTITION BY LIST (load_id);

CREATE TABLE static.trip (
    load_id integer NOT NULL,
    trip_id text NOT NULL,
    route_id text NOT NULL,
    service_id text NOT NULL,
    direction smallint,
    headsign text,
    short_name text,
    block_key text,
    run_key text,
    run_part smallint,
    wheelchair_accessible smallint,
    bikes_allowed smallint,
    shape_id text,
    PRIMARY KEY (load_id, trip_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.trip_call (
    load_id integer NOT NULL,
    trip_id text NOT NULL,
    sequence integer NOT NULL,
    location_id text NOT NULL,
    passenger_service boolean NOT NULL,
    boarding_point_id text,
    route_stop_id text,
    scheduled_arrival integer,
    scheduled_departure integer,
    pickup_type smallint NOT NULL,
    dropoff_type smallint NOT NULL,
    timepoint boolean NOT NULL,
    stop_headsign text,
    shape_distance_traveled double precision,
    subsidiary_code text,
    subsidiary_name text,
    active_line_code text,
    PRIMARY KEY (load_id, trip_id, sequence)
) PARTITION BY LIST (load_id);

CREATE TABLE static.route_stop (
    load_id integer NOT NULL,
    route_stop_id text NOT NULL,
    route_id text NOT NULL,
    direction smallint,
    sequence integer NOT NULL,
    location_id text NOT NULL,
    PRIMARY KEY (load_id, route_stop_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.route_stop_zone (
    load_id integer NOT NULL,
    route_stop_id text NOT NULL,
    source_order integer NOT NULL,
    zone_code text NOT NULL,
    zone_system text,
    PRIMARY KEY (load_id, route_stop_id, source_order)
) PARTITION BY LIST (load_id);

CREATE TABLE static.call_zone (
    load_id integer NOT NULL,
    trip_id text NOT NULL,
    sequence integer NOT NULL,
    source_order integer NOT NULL,
    zone_code text NOT NULL,
    zone_system text,
    PRIMARY KEY (load_id, trip_id, sequence, source_order)
) PARTITION BY LIST (load_id);

CREATE TABLE static.shape (
    load_id integer NOT NULL,
    shape_id text NOT NULL,
    generation_method text NOT NULL,
    PRIMARY KEY (load_id, shape_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.shape_point (
    load_id integer NOT NULL,
    shape_id text NOT NULL,
    sequence integer NOT NULL,
    longitude double precision NOT NULL,
    latitude double precision NOT NULL,
    distance_traveled double precision,
    PRIMARY KEY (load_id, shape_id, sequence)
) PARTITION BY LIST (load_id);

CREATE TABLE static.transfer (
    load_id integer NOT NULL,
    transfer_key text NOT NULL,
    from_location_id text,
    to_location_id text,
    from_route_id text,
    to_route_id text,
    from_trip_id text,
    to_trip_id text,
    transfer_type smallint NOT NULL,
    minimum_transfer_time integer,
    maximum_waiting_time integer,
    PRIMARY KEY (load_id, transfer_key)
) PARTITION BY LIST (load_id);

CREATE TABLE static.service_note (
    load_id integer NOT NULL,
    note_id text NOT NULL,
    kind text NOT NULL,
    label text,
    text text,
    valid_from date,
    valid_to date,
    service_note_type text,
    source_object_id text NOT NULL,
    PRIMARY KEY (load_id, note_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.assignment (
    load_id integer NOT NULL,
    assignment_id text NOT NULL,
    scope text NOT NULL,
    kind text NOT NULL,
    route_id text,
    trip_id text,
    call_sequence integer,
    call_sequence_to integer,
    service_id text,
    location_id text,
    source_code text,
    note_id text,
    source_object_id text,
    PRIMARY KEY (load_id, assignment_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.connection_claim (
    load_id integer NOT NULL,
    connection_id text NOT NULL,
    direction text NOT NULL,
    origin_trip_id text NOT NULL,
    origin_sequence integer NOT NULL,
    service_id text,
    target_source_route_id text,
    target_source_trip_id text,
    target_source_stop_id text,
    target_source_post_id text,
    target_source_end_stop_id text,
    target_source_end_post_id text,
    wait_minutes integer,
    note text,
    target_public_line text,
    target_destination_text text,
    target_derivation text NOT NULL,
    resolution_status text NOT NULL,
    target_route_id text,
    target_trip_id text,
    target_location_id text,
    source_object_id text NOT NULL,
    PRIMARY KEY (load_id, connection_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.travel_restriction (
    load_id integer NOT NULL,
    restriction_id text NOT NULL,
    scope text NOT NULL,
    route_id text,
    trip_id text,
    source_route_stop_id text NOT NULL,
    route_stop_id text,
    call_sequence integer,
    service_id text,
    group_code text NOT NULL,
    source_object_id text NOT NULL,
    PRIMARY KEY (load_id, restriction_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.source_key (
    load_id integer NOT NULL,
    entity_kind text NOT NULL,
    namespace text NOT NULL,
    identifier text NOT NULL,
    public_id text NOT NULL,
    valid_from date NOT NULL,
    valid_to date NOT NULL,
    binding_method text NOT NULL,
    PRIMARY KEY (load_id, namespace, identifier, public_id, valid_from, valid_to)
) PARTITION BY LIST (load_id);

CREATE TABLE static.call_key (
    load_id integer NOT NULL,
    namespace text NOT NULL,
    identifier text NOT NULL,
    source_sequence text NOT NULL,
    trip_id text NOT NULL,
    sequence integer NOT NULL,
    PRIMARY KEY (load_id, namespace, identifier, trip_id, source_sequence)
) PARTITION BY LIST (load_id);

CREATE TABLE static.service_date (
    load_id integer NOT NULL,
    service_id text NOT NULL,
    service_date date NOT NULL,
    PRIMARY KEY (load_id, service_date, service_id)
) PARTITION BY LIST (load_id);

CREATE TABLE static.shape_line (
    load_id integer NOT NULL,
    shape_id text NOT NULL,
    geom geometry(LineString, 4326) NOT NULL,
    PRIMARY KEY (load_id, shape_id)
) PARTITION BY LIST (load_id);

CREATE INDEX trip_call_location ON static.trip_call USING btree (load_id, location_id);
CREATE INDEX trip_route ON static.trip USING btree (load_id, route_id);
CREATE INDEX location_geom ON static.location USING gist (geom);
CREATE INDEX service_date_service ON static.service_date USING btree (load_id, service_id);

CREATE OR REPLACE VIEW active.agency AS
    SELECT agency_id, name, url, timezone, language, phone, fare_url, email
    FROM static.agency
    WHERE false;

CREATE OR REPLACE VIEW active.location AS
    SELECT location_id, kind, domain, parent_location_id, name, public_code, description, municipality_name, district_name, district_code, nearby_place, country_code, coordinate_precision, coordinate_source, longitude, latitude, url, timezone, wheelchair_boarding, geom
    FROM static.location
    WHERE false;

CREATE OR REPLACE VIEW active.route AS
    SELECT route_id, agency_id, mode, gtfs_route_type, short_name, long_name, description, url, color, text_color, sort_order, timetable_kind
    FROM static.route
    WHERE false;

CREATE OR REPLACE VIEW active.service_calendar AS
    SELECT service_id, valid_from, valid_to, weekday_mask
    FROM static.service_calendar
    WHERE false;

CREATE OR REPLACE VIEW active.service_exception AS
    SELECT service_id, service_date, added
    FROM static.service_exception
    WHERE false;

CREATE OR REPLACE VIEW active.trip AS
    SELECT trip_id, route_id, service_id, direction, headsign, short_name, block_key, run_key, run_part, wheelchair_accessible, bikes_allowed, shape_id
    FROM static.trip
    WHERE false;

CREATE OR REPLACE VIEW active.trip_call AS
    SELECT trip_id, sequence, location_id, passenger_service, boarding_point_id, route_stop_id, scheduled_arrival, scheduled_departure, pickup_type, dropoff_type, timepoint, stop_headsign, shape_distance_traveled, subsidiary_code, subsidiary_name, active_line_code
    FROM static.trip_call
    WHERE false;

CREATE OR REPLACE VIEW active.route_stop AS
    SELECT route_stop_id, route_id, direction, sequence, location_id
    FROM static.route_stop
    WHERE false;

CREATE OR REPLACE VIEW active.route_stop_zone AS
    SELECT route_stop_id, source_order, zone_code, zone_system
    FROM static.route_stop_zone
    WHERE false;

CREATE OR REPLACE VIEW active.call_zone AS
    SELECT trip_id, sequence, source_order, zone_code, zone_system
    FROM static.call_zone
    WHERE false;

CREATE OR REPLACE VIEW active.shape AS
    SELECT shape_id, generation_method
    FROM static.shape
    WHERE false;

CREATE OR REPLACE VIEW active.shape_point AS
    SELECT shape_id, sequence, longitude, latitude, distance_traveled
    FROM static.shape_point
    WHERE false;

CREATE OR REPLACE VIEW active.transfer AS
    SELECT transfer_key, from_location_id, to_location_id, from_route_id, to_route_id, from_trip_id, to_trip_id, transfer_type, minimum_transfer_time, maximum_waiting_time
    FROM static.transfer
    WHERE false;

CREATE OR REPLACE VIEW active.service_note AS
    SELECT note_id, kind, label, text, valid_from, valid_to, service_note_type, source_object_id
    FROM static.service_note
    WHERE false;

CREATE OR REPLACE VIEW active.assignment AS
    SELECT assignment_id, scope, kind, route_id, trip_id, call_sequence, call_sequence_to, service_id, location_id, source_code, note_id, source_object_id
    FROM static.assignment
    WHERE false;

CREATE OR REPLACE VIEW active.connection_claim AS
    SELECT connection_id, direction, origin_trip_id, origin_sequence, service_id, target_source_route_id, target_source_trip_id, target_source_stop_id, target_source_post_id, target_source_end_stop_id, target_source_end_post_id, wait_minutes, note, target_public_line, target_destination_text, target_derivation, resolution_status, target_route_id, target_trip_id, target_location_id, source_object_id
    FROM static.connection_claim
    WHERE false;

CREATE OR REPLACE VIEW active.travel_restriction AS
    SELECT restriction_id, scope, route_id, trip_id, source_route_stop_id, route_stop_id, call_sequence, service_id, group_code, source_object_id
    FROM static.travel_restriction
    WHERE false;

CREATE OR REPLACE VIEW active.source_key AS
    SELECT entity_kind, namespace, identifier, public_id, valid_from, valid_to, binding_method
    FROM static.source_key
    WHERE false;

CREATE OR REPLACE VIEW active.call_key AS
    SELECT namespace, identifier, source_sequence, trip_id, sequence
    FROM static.call_key
    WHERE false;

CREATE OR REPLACE VIEW active.service_date AS
    SELECT service_id, service_date
    FROM static.service_date
    WHERE false;

CREATE OR REPLACE VIEW active.shape_line AS
    SELECT shape_id, geom
    FROM static.shape_line
    WHERE false;
