"""Static mirror DDL generated from the serving contract.

Every contract relation becomes ``static.<relation>`` with a leading ``load_id`` and is
LIST-partitioned by it; each package load is one partition. Derived helpers follow the same
layout. ``active.<table>`` views expose the active release (see :mod:`obehy.release.activate`).

Run ``python -m obehy.release.ddl`` to regenerate the checked-in migration.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from obehy.release.contract import Contract, load_contract

MIGRATION = Path(__file__).resolve().parent / "migrations" / "0003_static.sql"
_IDENTIFIER = re.compile(r"^[a-z_][a-z0-9_]*$")


@dataclass(frozen=True)
class Column:
    name: str
    sql_type: str
    not_null: bool
    generated: str | None = None


@dataclass(frozen=True)
class Table:
    name: str
    columns: tuple[Column, ...]
    primary_key: tuple[str, ...]
    derived: bool = False

    @property
    def view_columns(self) -> tuple[str, ...]:
        return tuple(column.name for column in self.columns)


@dataclass(frozen=True)
class Index:
    name: str
    table: str
    columns: tuple[str, ...]
    method: Literal["btree", "gist"] = "btree"


LOCATION_GEOM = Column(
    "geom",
    "geometry(Point, 4326)",
    not_null=False,
    generated=(
        "CASE WHEN longitude IS NOT NULL AND latitude IS NOT NULL "
        "THEN ST_SetSRID(ST_MakePoint(longitude, latitude), 4326) END"
    ),
)

DERIVED_TABLES = (
    Table(
        "service_date",
        (
            Column("service_id", "text", not_null=True),
            Column("service_date", "date", not_null=True),
        ),
        primary_key=("service_date", "service_id"),
        derived=True,
    ),
    Table(
        "shape_line",
        (
            Column("shape_id", "text", not_null=True),
            Column("geom", "geometry(LineString, 4326)", not_null=True),
        ),
        primary_key=("shape_id",),
        derived=True,
    ),
)

# Lookup indexes beyond the primary keys. Inference-specific indexes come with the engine.
INDEXES = (
    Index("trip_call_location", "trip_call", ("load_id", "location_id")),
    Index("trip_route", "trip", ("load_id", "route_id")),
    Index("location_geom", "location", ("geom",), "gist"),
    Index("service_date_service", "service_date", ("load_id", "service_id")),
)


def static_tables(contract: Contract) -> tuple[Table, ...]:
    tables: list[Table] = []
    for relation in contract.relations:
        columns = tuple(
            Column(field.name, field.sql_type, not_null=not field.nullable)
            for field in relation.fields
        )
        if relation.name == "location":
            columns = (*columns, LOCATION_GEOM)
        tables.append(Table(relation.name, columns, relation.primary_key))
    tables.extend(DERIVED_TABLES)
    for table in tables:
        for name in (table.name, *table.view_columns):
            if not _IDENTIFIER.match(name):
                raise ValueError(f"Unsafe SQL identifier in the contract: {name!r}")
    return tuple(tables)


def column_definition(column: Column) -> str:
    text = f"{column.name} {column.sql_type}"
    if column.not_null:
        text += " NOT NULL"
    if column.generated is not None:
        text += f" GENERATED ALWAYS AS ({column.generated}) STORED"
    return text


def primary_key_columns(table: Table) -> tuple[str, ...]:
    return ("load_id", *table.primary_key)


def index_columns(index: Index) -> str:
    return ", ".join(index.columns)


def active_view(table: Table, load_ids: Sequence[int]) -> str:
    predicate = f"load_id IN ({', '.join(str(int(value)) for value in load_ids)})"
    if not load_ids:
        predicate = "false"
    return (
        f"CREATE OR REPLACE VIEW active.{table.name} AS\n"
        f"    SELECT {', '.join(table.view_columns)}\n"
        f"    FROM static.{table.name}\n"
        f"    WHERE {predicate};\n"
    )


def _lines(contract: Contract, tables: Iterable[Table]) -> Iterable[str]:
    # The mirror's DDL is that of the major's first version: a minor adding only namespaces or
    # enumeration values leaves it unchanged, so the applied migration keeps its checksum, and
    # a minor adding relations or fields gets a migration of its own.
    yield (
        f"-- Generated by `python -m obehy.release.ddl` from serving contract "
        f"{contract.version.split('.')[0]}.0. Do not edit.\n"
    )
    tables = tuple(tables)
    for table in tables:
        body = [
            "    load_id integer NOT NULL",
            *(f"    {column_definition(column)}" for column in table.columns),
            f"    PRIMARY KEY ({', '.join(primary_key_columns(table))})",
        ]
        yield f"\nCREATE TABLE static.{table.name} (\n"
        yield ",\n".join(body)
        yield "\n) PARTITION BY LIST (load_id);\n"
    yield "\n"
    for index in INDEXES:
        yield (
            f"CREATE INDEX {index.name} ON static.{index.table} "
            f"USING {index.method} ({index_columns(index)});\n"
        )
    for table in tables:
        yield "\n"
        yield active_view(table, ())


def static_ddl(contract: Contract | None = None) -> str:
    contract = contract or load_contract()
    return "".join(_lines(contract, static_tables(contract)))


def main() -> int:
    MIGRATION.write_text(static_ddl(), encoding="utf-8", newline="\n")
    print(MIGRATION)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
